# Generated by Django 5.2 on 2025-05-10 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Outflows',
            new_name='Outflow',
        ),
    ]
